name: build

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ 3.1, '3.0', 2.7, 2.6, head ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install libedit
      run: sudo apt-get install -q libedit-dev libedit2
      if: startsWith(matrix.os, 'ubuntu')
    - name: Install libedit
      run: brew install libedit
      if: startsWith(matrix.os, 'macos')
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        bundle install
        gem install reline --pre
    - name: Run test
      run: rake compile test
    - name: Run test with libedit enabled
      run: rake clobber compile test -- --enable-libedit
    - name: Run test with libedit disabled
      run: rake clobber compile test -- --disable-libedit
